//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApropriacaoHorasSEOEntities : DbContext
    {
        /*public ApropriacaoHorasSEOEntities()
            : base("name=ApropriacaoHorasSEOEntities")
        {
        }*/

        public ApropriacaoHorasSEOEntities(string nameOrConnectionString): base (nameOrConnectionString)
        {
            this.Database.Connection.ConnectionString = WebApi.Util.datasource;
        }

        /*protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }*/
    
        public virtual DbSet<SEO_ApropriacaoAtividade> SEO_ApropriacaoAtividade { get; set; }
        public virtual DbSet<SEO_ApropriacaoColaborador> SEO_ApropriacaoColaborador { get; set; }
        public virtual DbSet<SEO_Atividade> SEO_Atividade { get; set; }
        public virtual DbSet<SEO_AtividadeObra> SEO_AtividadeObra { get; set; }
        public virtual DbSet<SEO_AtividadeUsuario> SEO_AtividadeUsuario { get; set; }
        public virtual DbSet<SEO_Colaborador> SEO_Colaborador { get; set; }
        public virtual DbSet<SEO_Obras> SEO_Obras { get; set; }
        public virtual DbSet<SEO_Usuario> SEO_Usuario { get; set; }
        public virtual DbSet<SEO_UsuarioObra> SEO_UsuarioObra { get; set; }
    }
}
