//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SEO_Obras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEO_Obras()
        {
            this.SEO_ApropriacaoColaborador = new HashSet<SEO_ApropriacaoColaborador>();
            this.SEO_AtividadeObra = new HashSet<SEO_AtividadeObra>();
            this.SEO_UsuarioObra = new HashSet<SEO_UsuarioObra>();
        }

        [Key]
        public System.Guid O_Id { get; set; }
        public string O_Nome { get; set; }
        public string O_Codigo { get; set; }
        public bool O_Ativo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEO_ApropriacaoColaborador> SEO_ApropriacaoColaborador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEO_AtividadeObra> SEO_AtividadeObra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEO_UsuarioObra> SEO_UsuarioObra { get; set; }
    }
}
