//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SEO_Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEO_Usuario()
        {
            this.SEO_AtividadeUsuario = new HashSet<SEO_AtividadeUsuario>();
            this.SEO_UsuarioObra = new HashSet<SEO_UsuarioObra>();
        }

        [Key]
        public System.Guid U_Id { get; set; }
        public string U_Nome { get; set; }
        public string U_Email { get; set; }
        public string U_Chapa { get; set; }
        public string U_Password { get; set; }
        public string U_CPF { get; set; }
        public Nullable<System.Guid> U_Hash { get; set; }
        public string U_UserName { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEO_AtividadeUsuario> SEO_AtividadeUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEO_UsuarioObra> SEO_UsuarioObra { get; set; }
    }
}
