//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SEO_ApropriacaoColaborador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEO_ApropriacaoColaborador()
        {
            this.SEO_ApropriacaoAtividade = new HashSet<SEO_ApropriacaoAtividade>();
        }

        [Key]
        public System.Guid AC_id { get; set; }
        public System.Guid AC_IdColaborador { get; set; }
        public Nullable<decimal> AC_HorasPonto { get; set; }
        public System.DateTime AC_DataPonto { get; set; }
        public System.Guid AC_IdObra { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEO_ApropriacaoAtividade> SEO_ApropriacaoAtividade { get; set; }
        public virtual SEO_Colaborador SEO_Colaborador { get; set; }
        public virtual SEO_Obras SEO_Obras { get; set; }
    }
}
