//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SEO_AtividadeObra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEO_AtividadeObra()
        {
            this.SEO_AtividadeUsuario = new HashSet<SEO_AtividadeUsuario>();
        }

        [Key]
        public System.Guid AO_Id { get; set; }
        public System.Guid AO_IdAtividade { get; set; }
        public System.Guid AO_IdObra { get; set; }

        public virtual SEO_Atividade SEO_Atividade { get; set; }
        public virtual SEO_Obras SEO_Obras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEO_AtividadeUsuario> SEO_AtividadeUsuario { get; set; }
    }
}
