//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SEO_ApropriacaoAtividade
    {
        [Key]
        public System.Guid AA_Id { get; set; }
        public System.Guid AA_IdAtividade { get; set; }
        public Nullable<decimal> AA_HorasApropriadas { get; set; }
        public System.Guid AA_IdApropriacaoColaborador { get; set; }
        public Nullable<System.DateTime> AA_DataSincronizacao { get; set; }
    
        public virtual SEO_ApropriacaoColaborador SEO_ApropriacaoColaborador { get; set; }
        public virtual SEO_Atividade SEO_Atividade { get; set; }
    }
}
