//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SEO_Colaborador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEO_Colaborador()
        {
            this.SEO_ApropriacaoColaborador = new HashSet<SEO_ApropriacaoColaborador>();
        }

        [Key]
        public System.Guid C_Id { get; set; }
        public string C_Nome { get; set; }
        public string C_Chapa { get; set; }
        public bool C_Ativo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEO_ApropriacaoColaborador> SEO_ApropriacaoColaborador { get; set; }
    }
}
