//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SEO_Atividade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEO_Atividade()
        {
            this.SEO_ApropriacaoAtividade = new HashSet<SEO_ApropriacaoAtividade>();
            this.SEO_AtividadeObra = new HashSet<SEO_AtividadeObra>();
        }

        [Key]
        public System.Guid A_Id { get; set; }
        public string A_Nome { get; set; }
        public string A_Codigo { get; set; }
        public string A_Descricao { get; set; }
        public bool A_Ativo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEO_ApropriacaoAtividade> SEO_ApropriacaoAtividade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEO_AtividadeObra> SEO_AtividadeObra { get; set; }
    }
}
