//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SEO_UsuarioObra
    {
        [Key]
        public System.Guid UO_Id { get; set; }
        public System.Guid UO_IdUsuario { get; set; }
        public System.Guid UO_IdObra { get; set; }
        public bool UO_Ativo { get; set; }

        public virtual SEO_Obras SEO_Obras { get; set; }
        public virtual SEO_Usuario SEO_Usuario { get; set; }
    }
}
